version: '2'
services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      # POSTGRES_PASSWORD: '!--- config ---!'
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha20
    ports:
    - "8080:8080"
    depends_on:
    - "timescale"
    restart: always
    environment:
      # HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:!--config--!@timescale:5432/postgres
      # HASURA_GRAPHQL_ACCESS_KEY: '!--- set your access key ---!'
    command:
      - graphql-engine
      - serve
      - --enable-console
volumes:
  db_data:


